---
title: "DataEditing1219"
author: "Y.C"
date: "12/19/2021"
output: html_document
---

# Install packages
```{r packages}
library(data.table)
library(dplyr)
```



# Read in data
```{r}
load("CalculatedData.rda")
```

# Exclude 2007 and 2016
```{r}
CalculatedData <- CalculatedData %>%
  filter(FiscalYear!=2007,
         FiscalYear!=2016)
```


# Descriptive analysis

```{r how many herds and records }
CalculatedData %>% 
  summarise(herd=n_distinct(UBN),record=n())   #1887	12849	
```

```{r}
CalculatedData$IncomeOverFeedCostPer100Kg <- 100*(CalculatedData$TotalRevenues-CalculatedData$TotalFeedCosts)/CalculatedData$TotalMilkForFactoryKg
summary(CalculatedData)
```

# Filtering

```{r}
CalculatedData <- CalculatedData %>%
  group_by(UBN)%>%
  mutate(OrganicNumber=n_distinct(Organic),
         ProduceOwnProductNumber=n_distinct(ProduceOwnProduct),
         ProductTypeNumber=n_distinct(ProductType),
         YearDifferenceB=abs(LastyearInFlynth-as.numeric(FiscalYear)),
         YearDifferenceA=abs(NextyearInFlynth-as.numeric(FiscalYear))) %>%
  ungroup()

# consecutive year
FilteredData <- CalculatedData %>% 
  filter(YearDifferenceA==1 | YearDifferenceB==1)

FilteredData %>% 
  summarise(herd=n_distinct(UBN),record=n())   #1840	12665	
```



```{r}
FilteredData <- FilteredData %>%
  filter(ProduceOwnProduct!='ZUIVELAAR',
                            Organic!='BIO')
FilteredData %>% 
  summarise(herd=n_distinct(UBN),record=n())   #1817	12512	
```


```{r}
FilteredData <- FilteredData %>%
  filter(FlynthNumberOfMilkingCow>quantile(FlynthNumberOfMilkingCow,0.01))

Noconsecutive %>% 
  summarise(herd=n_distinct(UBN),record=n())
#1801	12386	
```



# Data for IOFC per cow

```{r IOFC per cow }
IOFCPerCow <- FilteredData %>%
  filter(HerdIntensity>quantile(HerdIntensity,0.01,na.rm = T),
         HerdIntensity<quantile(HerdIntensity,0.99,na.rm = T),
         Equity>quantile(Equity,0.01,na.rm = T)|is.na(Equity),
         M305>quantile(M305,0.01,na.rm = T),
         IncomeOverFeedCostPerCow>quantile(IncomeOverFeedCostPerCow,0.01,na.rm = T),
         IncomeOverFeedCostPerCow<quantile(IncomeOverFeedCostPerCow,0.99,na.rm = T),
         RelativeMilkPrice<quantile(RelativeMilkPrice,0.99,na.rm = T),
         AverageSCCPerYear<quantile(AverageSCCPerYear,0.99,na.rm = T)|is.na(AverageSCCPerYear),
         CalvingInterval<quantile(CalvingInterval,0.99,na.rm = T)|is.na(CalvingInterval),
         CalvingInterval>quantile(CalvingInterval,0.01,na.rm = T)|is.na(CalvingInterval),
         !is.na(NextyearInCRV),
         MedianPersistence1<quantile(MedianPersistence1,0.99,na.rm = T),
         MedianPersistence2<quantile(MedianPersistence2,0.99,na.rm = T)|is.na(MedianPersistence2),
         AverageAgeInDaysOfLivingCows<quantile(AverageAgeInDaysOfLivingCows,0.99,na.rm = T)|
         is.na(AverageAgeInDaysOfLivingCows),
         AverageAgeInDaysOfLivingCows>0|is.na(AverageAgeInDaysOfLivingCows))

IOFCPerCow %>% 
  summarise(herd=n_distinct(UBN),record=n())

# 1722	11036	

IOFCPerCow <- IOFCPerCow %>%
  select(UBN,FiscalYear,Successor,Robot,OutsourcingYoungStockRearing,SoilType,IncomeOverFeedCostPerCow,matches("(Persistence|Magnitude|TimeToPeak)"),FlynthNumberOfMilkingCow,HerdIntensity,Equity,,RelativeMilkPrice,AverageSCCPerYear,AverageAgeInDaysOfLivingCows,CalvingInterval,ExpansionRatePerYear,M305)
summary(IOFCPerCow)


IOFCPerCow <- na.omit(IOFCPerCow)
IOFCPerCow %>% 
  summarise(herd=n_distinct(UBN),record=n())

# 1673	10808	

save(IOFCPerCow,file="IOFCPerCow.rda")
```

# Data for IOFC per 100kg

```{r IOFC per 100kg}
IOFCPer100Kg <- FilteredData %>%
  filter(HerdIntensity>quantile(HerdIntensity,0.01,na.rm = T),
         HerdIntensity<quantile(HerdIntensity,0.99,na.rm = T),
         Equity>quantile(Equity,0.01,na.rm = T)|is.na(Equity),
         M305>quantile(M305,0.01,na.rm = T),
         IncomeOverFeedCostPer100Kg>quantile(IncomeOverFeedCostPer100Kg,0.01,na.rm = T),
         IncomeOverFeedCostPer100Kg<quantile(IncomeOverFeedCostPer100Kg,0.99,na.rm = T),
         RelativeMilkPrice<quantile(RelativeMilkPrice,0.99,na.rm = T),
         AverageSCCPerYear<quantile(AverageSCCPerYear,0.99,na.rm = T)|is.na(AverageSCCPerYear),
         CalvingInterval<quantile(CalvingInterval,0.99,na.rm = T)|is.na(CalvingInterval),
         CalvingInterval>quantile(CalvingInterval,0.01,na.rm = T)|is.na(CalvingInterval),
         !is.na(NextyearInCRV),
         MedianPersistence1<quantile(MedianPersistence1,0.99,na.rm = T),
         MedianPersistence2<quantile(MedianPersistence2,0.99,na.rm = T)|is.na(MedianPersistence2),
         AverageAgeInDaysOfLivingCows<quantile(AverageAgeInDaysOfLivingCows,0.99,na.rm = T)|
         is.na(AverageAgeInDaysOfLivingCows),
         AverageAgeInDaysOfLivingCows>0|is.na(AverageAgeInDaysOfLivingCows))

IOFCPer100Kg %>% 
  summarise(herd=n_distinct(UBN),record=n())

# 1723	11053	

IOFCPer100Kg <- IOFCPer100Kg %>%
  select(UBN,FiscalYear,Successor,Robot,OutsourcingYoungStockRearing,SoilType,IncomeOverFeedCostPer100Kg,matches("(Persistence|Magnitude|TimeToPeak)"),FlynthNumberOfMilkingCow,HerdIntensity,Equity,,RelativeMilkPrice,AverageSCCPerYear,AverageAgeInDaysOfLivingCows,CalvingInterval,ExpansionRatePerYear,M305)

IOFCPer100Kg<- na.omit(IOFCPer100Kg)
IOFCPer100Kg %>% 
  summarise(herd=n_distinct(UBN),record=n())

# 1672	10826	

save(IOFCPer100Kg,file="IOFCPer100Kg.rda")
```
