
```{r packages}
library('data.table')
library('dplyr')
library(ggplot2)
library(psych) #describe的来源
library(lme4)
library(usethis)
library(lmerTest)
library(nlme)
library(MuMIn)
library(car)
library(sjPlot) 
library(lavaan)
library(lmtest)
library(effects)
#install.packages('jtools')
library(jtools)
rm(list = ls())
```

# data import
```{r}
load("FinalData.rda")
```

```{r decriptive}
FinalData  %>% 
  summarise(herd=n_distinct(UBN),record=n())  #1664	10499	

FinalData %>%
  group_by(FiscalYear) %>%
  summarise(mean(IncomeOverFeedCostPerCow))


FinalData %>%
  group_by(FiscalYear) %>%
  summarise_each(funs(mean(.), sd(.), NROW(.)), matches('Median'))

FinalData %>%
  summarise_each(funs(mean(.), sd(.), NROW(.)), matches('Median'))

FinalData %>%
  group_by(FiscalYear) %>%
  summarise(mean(IncomeOverFeedCostPer100Kg))

sd(FinalData$IncomeOverFeedCostPer100Kg)

FinalData %>%
  mutate(IncomeOverFeedCostPerCowPerDay=IncomeOverFeedCostPerCow/365)%>%
  summarise(mean(IncomeOverFeedCostPerCowPerDay),
            mean(IncomeOverFeedCostPerCow),
            sd(IncomeOverFeedCostPerCowPerDay),
            sd(IncomeOverFeedCostPerCow))

FinalData %>% group_by(FiscalYear)%>%
  summarise(mean(IncomeOverFeedCostPerCow),
            sd(IncomeOverFeedCostPerCow),
            length(IncomeOverFeedCostPerCow))


FinalData %>% group_by(FiscalYear)%>%
  summarise(mean(IncomeOverFeedCostPer100Kg),
            sd(IncomeOverFeedCostPer100Kg),
            length(IncomeOverFeedCostPer100Kg))
```

```{r decriptive}
library(tidyr)
options(scipen=2)
FinalData %>%
  select(M305,CalvingInterval,Equity,HerdIntensity,RelativeMilkPrice,IncomeOverFeedCostPerCow,IncomeOverFeedCostPer100Kg,FlynthNumberOfMilkingCow,ExpansionRatePerYear,AverageAgeInDaysOfLivingCows,AverageSCCPerYear,MedianMagnitude1,MedianTimeToPeak1,MedianPersistence1,MedianMagnitude2,MedianTimeToPeak2,MedianPersistence2)%>%
  pivot_longer(cols = everything()) %>% 
    group_by(name) %>%
    summarise(across(value, list(mean= ~ mean(., na.rm = TRUE), 
         sd = ~ sd(., na.rm = TRUE), 
         quantile = ~ list(as_tibble(as.list(quantile(., 
                   probs = c(0.05,0.95)))))))) %>% 
unnest(c(value_quantile))
```

```{r correlation}

library(corrplot)
cor<-cor(FinalData[c(7:23)] ,use = "pairwise.complete.obs")
corp <- cor.mtest(FinalData[c(7:23)], conf.level = 0.95)
p.mat = corp$p

corrplot(cor, order = "FPC", method = "color",
tl.col="black",tl.cex = 0.6,cl.pos = "r",cl.ratio = 0.2,
sig.level = .05,insig = "blank",addgrid.col="white")
summary(FinalData)
```

```{r characterize catergory variables}
cols <- c('UBN','FiscalYear', 'Successor', 'Robot')
FinalData[cols] <- lapply(FinalData[cols], as.character)
colnames(FinalData)
```

```{r standardization all indepent variables and remove na}
colnames(FinalData)
FinalData[c(9:23)] <- scale(FinalData[c(9:23)])
summary(FinalData)
data <- na.omit(FinalData)
plot(data$ExpansionRatePerYear,data$IncomeOverFeedCostPerCow)
```

# IOFC per 100kg milk


```{r random effect}
lmWithRandom <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN), data=data, REML=F)
lmWithoutRandom <-lm(IncomeOverFeedCostPer100Kg~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows , data=data)
anova(lmWithRandom,lmWithoutRandom)
# decision: add random effect
```


```{r repeated statement}
lmWithoutRepeatedStatement <-lmer(IncomeOverFeedCostPer100Kg  ~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN), data=data, REML=F)

lmWithRepeatedStatement <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1  + as.numeric(FiscalYear)|UBN), data=data, REML=F)

anova(lmWithoutRepeatedStatement,lmWithRepeatedStatement)
# decision: no repeated statement
```


#1. basic model 

```{r backward selection}
lm <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN), data=data, REML=F)

vif(lm) #1.00~1.40
step(lm)
drop1(lm, test="Chisq")

back1<-update(lm, .~.-FlynthNumberOfMilkingCow-Robot-Successor,data=data) 
drop1(back1, test="Chisq")

summary(back1)
# delete -FlynthNumberOfMilkingCow-Successor-Robot
```


#2. basic + HLCC

```{r backward selection}
lm <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + SoilType + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN) + MedianMagnitude1 +MedianTimeToPeak1+MedianPersistence1+MedianMagnitude2 +MedianTimeToPeak2+MedianPersistence2, data=data, REML=F)
vif(lm) #1.00-1.47
drop1(lm, test="Chisq") # drop nothing
qqnorm(residuals(lm))
options(scipen=3)
summary(lm)
r.squaredGLMM(lm)

```

```{r partR2}
## PartR2 for individual predictor
partR2(lm,
       partvars = c('MedianMagnitude1','MedianTimeToPeak1','MedianPersistence1'),
       data=data,
       R2_type = "marginal")
partR2(lm,
       partvars = c('MedianMagnitude2','MedianTimeToPeak2','MedianPersistence2'),
       data=data,
       R2_type = "marginal")
partR2(lm,
       partvars = c('FiscalYear'),
       data=data,
       R2_type = "marginal")
partR2(lm,
       partvars = c('RelativeMilkPrice'),
       data=data,
       R2_type = "marginal")
partR2(lm,
       partvars = c('HerdIntensity '),
       data=data,
       R2_type = "marginal")
```


#3. basic + M305
```{r backward selection}
lmM305 <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + SoilType + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN) + M305, data=data, REML=F)
vif(lmM305) #1.00-1.4
drop1(lmM305, test="Chisq") # drop nothing
qqnorm(residuals(lmM305))
options(scipen=3)
summary(lmM305)
r.squaredGLMM(lmM305)

```

```{r partR2}
## PartR2 for individual predictor
partR2(lmM305,
       partvars = c('M305'),
       data=data,
       R2_type = "marginal")
partR2(lmM305,
       partvars = c('FiscalYear'),
       data=data,
       R2_type = "marginal")
partR2(lmM305,
       partvars = c('RelativeMilkPrice'),
       data=data,
       R2_type = "marginal")
partR2(lmM305,
       partvars = c('HerdIntensity '),
       data=data,
       R2_type = "marginal")
```


# compare two non-nested models

```{r}
model_lme100kg<-lme(IncomeOverFeedCostPer100Kg ~ FiscalYear + SoilType + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + MedianMagnitude1 +MedianTimeToPeak1+MedianPersistence1+MedianMagnitude2 +MedianTimeToPeak2+MedianPersistence2, data=data, random =~1|UBN, control = lmeControl(opt='optim') ,method = 'ML')

vif(model_lme100kg) #1.00-1.47
drop1(model_lme100kg, test="Chisq") #drop nothing
summary(model_lme100kg)

model_lmeM305100kg<-lme(IncomeOverFeedCostPer100Kg ~ FiscalYear + SoilType + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + M305, data=data, random =~1|UBN, control = lmeControl(opt='optim') ,method = 'ML')
drop1(model_lmeM305100kg, test="Chisq")#drop nothing
summary(model_lmeM305100kg)

coxtest(model_lme100kg,model_lmeM305100kg, data = data)
jtest(model_lme100kg,model_lmeM305100kg, data = data)
```

# interaction (not found any representative yet)  m vs Intensity expansion 2

```{r M3 median interaction}
lminteraction1 <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + SoilType  + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN)+ MedianMagnitude1 +MedianTimeToPeak1+MedianPersistence1+MedianMagnitude2 +MedianTimeToPeak2+MedianPersistence2 + MedianMagnitude1*ExpansionRatePerYear + MedianMagnitude2*ExpansionRatePerYear , data=data, REML=F)

lminteraction2 <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + SoilType  + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN)+ MedianMagnitude1 +MedianTimeToPeak1+MedianPersistence1+MedianMagnitude2 +MedianTimeToPeak2+MedianPersistence2 + MedianMagnitude2*HerdIntensity  , data=data, REML=F)

anova(lminteraction1,back1)
summary(lminteraction1)
plot_model(lminteraction1,type = "pred",terms = c("MedianMagnitude1","CalvingInterval"))
plot_model(lminteraction1,type = "int")
plot_model(lminteraction1,type = "int", mdrt.values ='meansd')

anova(lminteraction2,back1)
summary(lminteraction2)
plot_model(lminteraction2,type = "pred",terms = c("MedianPersistence2","HerdIntensity"))
plot_model(lminteraction2,type = "int")
plot_model(lminteraction2,type = "int", mdrt.values ='meansd')
```

