
---
title: "R Notebook"
output: html_notebook
---

```{r packages}
library('data.table')
library('dplyr')
library(ggplot2)
library(psych) #describe的来源
library(lme4)
library(usethis)
library(lmerTest)
library(nlme)
library(MuMIn)
library(car)
library(sjPlot)
#library(MASS)
```

# data import
```{r}
load("IOFCPer100Kg.rda")
SelectedData <- IOFCPer100Kg
```


```{r decriptive}
SelectedData  %>% 
  summarise(herd=n_distinct(UBN),record=n())

SelectedData %>%
  group_by(FiscalYear) %>%
  summarise(mean(IncomeOverFeedCostPer100Kg))


SelectedData %>%
  group_by(FiscalYear) %>%
  summarise_each(funs(mean(.), sd(.), NROW(.)), matches('Median'))

SelectedData %>%
  summarise_each(funs(mean(.), sd(.), NROW(.)), matches('Median'))
```


```{r decriptive}
library(tidyr)
IOFCPer100Kg %>%
  select(IncomeOverFeedCostPer100Kg)%>%
  pivot_longer(cols = everything()) %>% 
    group_by(name) %>%
    summarise(across(value, list(mean= ~ mean(., na.rm = TRUE), 
         sd = ~ sd(., na.rm = TRUE), 
         quantile = ~ list(as_tibble(as.list(quantile(., 
                   probs = c(0.05,0.95)))))))) %>% 
unnest(c(value_quantile))

options(scipen=5)
```


```{r characterize catergory variables}
cols <- c('UBN','FiscalYear', 'Successor', 'Robot')
SelectedData[cols] <- lapply(SelectedData[cols], as.character)
colnames(SelectedData)
```

```{r correlation}

library(corrplot)
cor<-cor(SelectedData[c(7:28)] ,use = "pairwise.complete.obs")
corp <- cor.mtest(SelectedData[c(7:28)], conf.level = 0.95)
p.mat = corp$p

corrplot(cor, order = "FPC", method = "color",
tl.col="black",tl.cex = 0.6,cl.pos = "r",cl.ratio = 0.2,
sig.level = .05,insig = "blank",addgrid.col="white")
summary(SelectedData)
```


```{r standardization all indepent variables and remove na}
colnames(SelectedData)
SelectedData[c(8:28)] <- scale(SelectedData[c(8:28)])
summary(SelectedData)
data <- na.omit(SelectedData)
```


# IOFC per100kg
```{r random effect}
lmWithRandom <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN), data=data, REML=F)
lmWithoutRandom <-lm(IncomeOverFeedCostPer100Kg~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows , data=data)
anova(lmWithRandom,lmWithoutRandom)
# decision: add random effect
```


```{r repeated statement}
lmWithoutRepeatedStatement <-lmer(IncomeOverFeedCostPer100Kg  ~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN), data=data, REML=F)

lmWithRepeatedStatement <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1  + as.numeric(FiscalYear)|UBN), data=data, REML=F)

anova(lmWithoutRepeatedStatement,lmWithRepeatedStatement)
# decision: no repeated statement
```



```{r}
lm2 <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + Successor+ FlynthNumberOfMilkingCow + SoilType + Robot + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN)+ MedianMagnitude1 +MedianTimeToPeak1+MedianPersistence1+MedianMagnitude2 +MedianTimeToPeak2+MedianPersistence2, data=data, REML=F)
drop1(lm2, test="Chisq")
back1<-update(lm2, .~.-Robot-FlynthNumberOfMilkingCow-Successor,data=data) 
drop1(back1, test="Chisq")
qqnorm(residuals(back1))
summary(back1)
r.squaredGLMM(back1)

partR2(back1,
       partvars = c('MedianMagnitude1','MedianTimeToPeak1','MedianPersistence1'),
       data=data,
       R2_type = "marginal")
partR2(back1,
       partvars = c('MedianMagnitude2','MedianTimeToPeak2','MedianPersistence2'),
       data=data,
       R2_type = "marginal")

partR2(back1,
       partvars = c('FiscalYear'),
       data=data,
       R2_type = "marginal")
partR2(back1,
       partvars = c('RelativeMilkPrice'),
       data=data,
       R2_type = "marginal")
partR2(back1,
       partvars = c('HerdIntensity '),
       data=data,
       R2_type = "marginal")
```


# interaction

```{r M3 median interaction}
lminteraction1 <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + SoilType  + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN)+ MedianMagnitude1 +MedianTimeToPeak1+MedianPersistence1+MedianMagnitude2 +MedianTimeToPeak2+MedianPersistence2 + MedianMagnitude1*ExpansionRatePerYear + MedianMagnitude2*ExpansionRatePerYear , data=data, REML=F)

lminteraction2 <-lmer(IncomeOverFeedCostPer100Kg ~ FiscalYear + SoilType  + AverageSCCPerYear + Equity + OutsourcingYoungStockRearing  + HerdIntensity + CalvingInterval + RelativeMilkPrice + ExpansionRatePerYear  +  AverageAgeInDaysOfLivingCows + (1|UBN)+ MedianMagnitude1 +MedianTimeToPeak1+MedianPersistence1+MedianMagnitude2 +MedianTimeToPeak2+MedianPersistence2 + MedianMagnitude1*ExpansionRatePerYear  , data=data, REML=F)

anova(lminteraction1,back1)
summary(lminteraction1)
plot_model(lminteraction1,type = "pred",terms = c("MedianMagnitude2","ExpansionRatePerYear"))
plot_model(lminteraction1,type = "int")
plot_model(lminteraction1,type = "int", mdrt.values ='meansd')

anova(lminteraction2,back1)
summary(lminteraction2)
plot_model(lminteraction2,type = "pred",terms = c("MedianMagnitude1","ExpansionRatePerYear"))
plot_model(lminteraction2,type = "int")
plot_model(lminteraction2,type = "int", mdrt.values ='meansd')
```